-- specs/softcut_runtime_spec.lua
-- Tests for the softcut buffer management runtime.

package.path = package.path .. ";./?.lua"

local softcut_runtime = require("lib/voices/softcut_runtime")

describe("softcut_runtime", function()

  describe("buffer allocation", function()
    it("creates 6 voice slots by default", function()
      local rt = softcut_runtime.new()
      assert.are.equal(6, rt.num_voices)
      assert.is_not_nil(rt.voices[1])
      assert.is_not_nil(rt.voices[6])
      assert.is_nil(rt.voices[7])
    end)

    it("splits voices across 2 buffers", function()
      local rt = softcut_runtime.new()
      -- Voices 1-3 on buffer 1, 4-6 on buffer 2
      assert.are.equal(1, rt.voices[1].buffer)
      assert.are.equal(1, rt.voices[2].buffer)
      assert.are.equal(1, rt.voices[3].buffer)
      assert.are.equal(2, rt.voices[4].buffer)
      assert.are.equal(2, rt.voices[5].buffer)
      assert.are.equal(2, rt.voices[6].buffer)
    end)

    it("assigns non-overlapping fixed regions", function()
      local rt = softcut_runtime.new()
      local region_dur = rt.buffer_dur / 3

      -- Buffer 1: three equal regions
      assert.are.equal(0, rt.voices[1].region_start)
      assert.are.equal(region_dur, rt.voices[1].region_end)
      assert.are.equal(region_dur, rt.voices[2].region_start)
      assert.are.equal(2 * region_dur, rt.voices[2].region_end)
      assert.are.equal(2 * region_dur, rt.voices[3].region_start)
      assert.are.equal(3 * region_dur, rt.voices[3].region_end)

      -- Buffer 2: same layout
      assert.are.equal(0, rt.voices[4].region_start)
      assert.are.equal(region_dur, rt.voices[4].region_end)
    end)

    it("accepts custom voice count", function()
      local rt = softcut_runtime.new({num_voices = 4})
      assert.are.equal(4, rt.num_voices)
      assert.is_not_nil(rt.voices[4])
      assert.is_nil(rt.voices[5])
      -- 4 voices: 2 per buffer
      assert.are.equal(1, rt.voices[1].buffer)
      assert.are.equal(1, rt.voices[2].buffer)
      assert.are.equal(2, rt.voices[3].buffer)
      assert.are.equal(2, rt.voices[4].buffer)
    end)
  end)

  describe("voice state", function()
    it("tracks enable state", function()
      local rt = softcut_runtime.new()
      assert.is_false(rt.voices[1].enabled)
      rt.enable(1, true)
      assert.is_true(rt.voices[1].enabled)
    end)

    it("tracks level and pan", function()
      local rt = softcut_runtime.new()
      rt.level(1, 0.75)
      rt.pan(1, -0.5)
      assert.are.equal(0.75, rt.voices[1].level)
      assert.are.equal(-0.5, rt.voices[1].pan)
    end)

    it("tracks playback state", function()
      local rt = softcut_runtime.new()
      rt.play(1, true)
      rt.rate(1, 2.0)
      rt.position(1, 1.5)
      assert.is_true(rt.voices[1].playing)
      assert.are.equal(2.0, rt.voices[1].rate)
      assert.are.equal(1.5, rt.voices[1].position)
    end)

    it("tracks loop settings", function()
      local rt = softcut_runtime.new()
      rt.loop(1, true)
      rt.loop_start(1, 0.5)
      rt.loop_end(1, 2.5)
      assert.is_true(rt.voices[1].loop)
      assert.are.equal(0.5, rt.voices[1].loop_start)
      assert.are.equal(2.5, rt.voices[1].loop_end)
    end)

    it("tracks slew/fade times", function()
      local rt = softcut_runtime.new()
      rt.fade_time(1, 0.1)
      rt.level_slew_time(1, 0.2)
      rt.rate_slew_time(1, 0.3)
      assert.are.equal(0.1, rt.voices[1].fade_time)
      assert.are.equal(0.2, rt.voices[1].level_slew_time)
      assert.are.equal(0.3, rt.voices[1].rate_slew_time)
    end)

    it("ignores operations on invalid voice ids", function()
      local rt = softcut_runtime.new()
      -- Should not error
      rt.enable(99, true)
      rt.level(99, 1)
      rt.play(99, true)
    end)
  end)

  describe("sample loading", function()
    it("loads a sample when the file exists", function()
      local rt = softcut_runtime.new({file_exists = function() return true end})
      local ok, err = rt.load_sample(1, "/tmp/test.wav", {start_sec = 0, end_sec = 1})
      assert.is_true(ok)
      assert.is_nil(err)
      assert.is_true(rt.voices[1].sample_loaded)
      assert.are.equal("/tmp/test.wav", rt.voices[1].sample_path)
    end)

    it("fails when the file does not exist", function()
      local rt = softcut_runtime.new({file_exists = function() return false end})
      local ok, err = rt.load_sample(1, "/tmp/missing.wav", {start_sec = 0, end_sec = 1})
      assert.is_false(ok)
      assert.are.equal("file_not_found", err)
      assert.is_false(rt.voices[1].sample_loaded)
    end)

    it("fails on invalid voice id", function()
      local rt = softcut_runtime.new({file_exists = function() return true end})
      local ok, err = rt.load_sample(99, "/tmp/test.wav", {start_sec = 0, end_sec = 1})
      assert.is_false(ok)
      assert.are.equal("invalid_voice", err)
    end)
  end)

  describe("file_exists", function()
    it("uses injected checker when provided", function()
      local checked = {}
      local rt = softcut_runtime.new({file_exists = function(p)
        table.insert(checked, p)
        return p == "/yes"
      end})
      assert.is_true(rt.file_exists("/yes"))
      assert.is_false(rt.file_exists("/no"))
      assert.are.same({"/yes", "/no"}, checked)
    end)

    it("returns false for nil or empty path", function()
      local rt = softcut_runtime.new()
      assert.is_false(rt.file_exists(nil))
      assert.is_false(rt.file_exists(""))
    end)
  end)

  describe("no-op methods", function()
    it("rec_level and pre_level accept calls without error", function()
      local rt = softcut_runtime.new()
      rt.rec_level(1, 0.5)
      rt.pre_level(1, 0.8)
      rt.level_cut(1, 2, 0.5)
    end)
  end)

  describe("warn", function()
    it("collects warnings", function()
      local rt = softcut_runtime.new()
      rt.warn("test warning")
      rt.warn("another")
      assert.are.same({"test warning", "another"}, rt.warnings)
    end)
  end)

  describe("platform mode", function()
    local orig_softcut

    before_each(function()
      orig_softcut = rawget(_G, "softcut")
      rawset(_G, "softcut", nil)
    end)

    after_each(function()
      rawset(_G, "softcut", orig_softcut)
    end)

    it("detects dry mode when _G.softcut is absent", function()
      assert.are.equal("dry", softcut_runtime.detect_mode())
    end)

    it("detects norns mode when _G.softcut is present with expected API", function()
      rawset(_G, "softcut", { enable = function() end })
      assert.are.equal("norns", softcut_runtime.detect_mode())
    end)

    it("stores the mode on the runtime", function()
      local rt = softcut_runtime.new()
      assert.are.equal("dry", rt.mode)
      assert.is_true(rt.is_dry())
    end)

    it("accepts an explicit mode override", function()
      local rt = softcut_runtime.new({ mode = "norns" })
      assert.are.equal("norns", rt.mode)
      assert.is_false(rt.is_dry())
    end)

    it("status_string describes the active mode", function()
      local dry = softcut_runtime.status_string("dry")
      local native = softcut_runtime.status_string("norns")
      assert.is_truthy(dry:match("dry"))
      assert.is_truthy(native:match("norns"))
    end)

    it("announce() prints without error on either mode", function()
      assert.has_no.errors(function()
        softcut_runtime.announce("dry")
        softcut_runtime.announce("norns")
      end)
    end)
  end)
end)
